-- After much thought, I came up with a split configuration that can be changed piecemeal.
-- That's what this script is for.
-- This file is the entry point to the configuration.
--
-- Project structure, which shows which files and directories are contained in the project (eza -T):
-- ├── init.lua
-- └── lua
--     ├── config
--     │   ├── keymaps.lua
--     │   ├── lazy.lua
--     │   └── options.lua
--     └── plugins
--         ├── cmp.lua
--         ├── codeium.lua
--         ├── color.lua
--         ├── fzf.lua
--         ├── lsp.lua
--         ├── mason.lua
--         ├── neogit.lua
--         ├── statusline.lua
--         ├── surround.lua
--         ├── tmux_navigator.lua
--         ├── treesitter.lua
--         ├── treesitter_textobjects.lua
--         ├── trouble.lua
--         └── whick_key.lua
require 'config.lazy'
