#!/bin/bash

DEFAULT_PATH="$HOME/Downloads/Git/minvim/"
LINK_PATH="$DEFAULT_PATH"

CONFIG="$HOME/.config"
NVIM_PATH="$CONFIG/nvim"

OS=$(uname -s)

read -p "Do you want to install neovim? (y/n) " ans
if [[ "$ans" = "y" ]]
then
    case "$OS" in
        *"Arch"*) 
            yes | sudo pacman -Suy neovim unzip git
            ;;
        *"Fedora"*)
            sudo dnf update -y && sudo dnf upgrade -y
            sudo dnf install neovim unzip git -y
            ;;
        *"Ubuntu"*)
            sudo apt-get update && sudo apt-get upgrade
            sudo apt-get install neovim unzip git
            echo "Change distro bro"
            ;;
        *) 
            echo "Distro not supported"
            exit 1
            ;;
    esac
fi



if [[ ! -d "$CONFIG" ]]
then
    echo "$CONFIG not found. Creating"
    mkdir -p "$CONFIG"
fi

if [[ -d "$NVIM_PATH" ]]
then
    # Update by default
    echo "Deleting old version..."
    rm -rf "$NVIM_PATH"
fi

if [[ -z "$1" ]]
then
    read -p "Do you want to use default path ($DEFAULT_PATH)? (y/n) " ans

    if [[ ! "$ans" = ^[yY]$ ]]
    then
        echo "Provide path to linking files"
        echo "Example:"
        echo "  ./setup-nvim $DEFAULT_PATH"
    fi
else
    LINK_PATH="$1"
fi

echo "Linking config file..."

ln -s "$LINK_PATH" "$NVIM_PATH"

echo "Done!"
